name: air_state
description: A lightweight, modular state management library for the Air Framework.
version: 1.0.1
homepage: https://github.com/AndreyDAraya/air-state
repository: https://github.com/AndreyDAraya/air-state

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - state-management
  - reactive
  - flutter
  - air

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
